[workspace]
resolver = "2"

members = [
    "vector-trees",
    "scrape-solana"
]

[profile.release]
debug = true

[profile.release.package.vector-trees]
overflow-checks = true

[profile.release.package.scrape-solana]
overflow-checks = true
