[package]
name = "huge-vec"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.213", features = ["derive"] }
bincode = "1.3.3"
zstd = "0.13.2"
tempfile = "3.13.0"
rayon = "1.10.0"
thiserror = "1.0.65"
